### ISSUE TITLE
German language generation

### ISSUE THREAD

**Issue by emnullfuenf** [spiglerg/RNN_Text_Generation_Tensorflow#4]
I tried to generate German text. Unfortunately the results are only extracts from the original text. But no generated new remixes.

For testing i used Wagner's Lohengrin (old German) and German Hip Hop lyrics (of one group). In order to verify i successfully tried Vernor Vinges Rainbows End in English language. #

**Comment by spiglerg** [comment]
Well, the network can only learn to generate text with statistics similar to the training data, so it shouldn't be able to generalize to significantly different statistics (e.g., train on normal text, generate musical lyrics).

In any case, the network generating full extracts from the original text might be a result of some slight overfitting. You may want to try using more layers and/or more units per layer.

PS: do you mean that you used sentence beginnings form the other texts for 'testing'?

**Comment by emnullfuenf** [comment]
Thanks for the hints.
I increased the size of the training data and tested an Umberto Eco book (in German language). The result really sounds like Eco with some interesting new coined words.
Thus i have to increase the training data for Wagner and Hip Hop, too.

**Comment by spiglerg** [comment]
Awesome. :)

**Comment by emnullfuenf** [comment]
I still have problems with short texts. The results are always original sentences from the data.

My current text has 150.000 characters and 21.000 words. It's a collection of articles of one news paper author about a certain topic.

These are my current parameters:
in_size = out_size = len(vocab)
lstm_size = 256 #256 #128
num_layers = 2 #2
batch_size = 256 #128
time_steps = 100 #50
NUM_TRAIN_BATCHES = 20000
LEN_TEST_TEXT = 1000

I already tried these parameters:
lstm_size 128 -> 256
num_layers 2 -> 4
NUM_TRAIN_BATCHES 20000 -> 40000

**Comment by spiglerg** [comment]
Hmm if the sentences are the actual exact ones from the dataset then it sounds like overfitting. Maybe you can try to use fewer units and layers, or using some form of regularization?

**Comment by emnullfuenf** [comment]
Thanks. Now it works fine with these settings:
lstm_size = 128 #shorter text 256 for longer texts
num_layers = 2
batch_size = 256
time_steps = 100
NUM_TRAIN_BATCHES = 80000
