### ISSUE TITLE
Object duplication in MultiRNNCell declaration

### ISSUE THREAD

**Issue by therealjtgill** [spiglerg/RNN_Text_Generation_Tensorflow#5]
Hi spiglerg!

First off, I want to say that your code has helped me become much more familiar with the RNN framework inside of Tensorflow. Thank you!

I noticed that on line [47](https://github.com/spiglerg/RNN_Text_Generation_Tensorflow/blob/master/rnn_tf.py#L47) of rnn_tf.py you create a two-element list of LSTM cells by saying:
`[self.lstm_cell]*self.num_layers`
Which creates a list of two of the exact same TF objects. Since each TF object has its own set of trainable parameters, won't duplicating the same TF object cause the network to have two layers of LSTM cells that have the exact same parameters?

**Comment by spiglerg** [comment]
I don't think it's a problem as BasicLSTMCell parameters are initialized within their __call__ function, which is only called from dynamic_run().

**Comment by therealjtgill** [comment]
Nice, thanks!

**Comment by therealjtgill** [comment]
Just wanted to add that the new r1.0 API doesn't let you use the notation [self.lstm_cell]*num_layers any more. You have to create a list of different lstm_cell objects, then pass then to dynamic_rnn.

**Comment by spiglerg** [comment]
Hmm do you have any reference?
I don't think it is a problem with BasicLSTMCell (as long as all the LSTMs have the same parameters, e.g., number of units). Indeed lstm_cell.call() creates a new part of the graph every time it's called, without modifying any object's fields.

**Comment by spiglerg** [comment]
In general though you are right, so it may be cleaner to replace with with a list iteration. :)

**Comment by therealjtgill** [comment]
Reference: Line 48 in the core_rnn_cell implementation raises a ValueError for duplicating the same layer object.

https://github.com/tensorflow/tensorflow/blob/b10f50ff15944badb7262a207f6628dfa52d6a9d/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py#L48

**Comment by spiglerg** [comment]
Hmm from where is that called?
Is it due to the new line 46 in the code?
`self.lstm_cells = [ tf.contrib.rnn.BasicLSTMCell(self.lstm_size, forget_bias=1.0, state_is_tuple=False) for i in range(self.num_layers)]`

**Comment by therealjtgill** [comment]
Oh! The new code doesn't generate any errors. But the old version would have. Sorry for the confusion.

**Comment by spiglerg** [comment]
Awesome. :)
